[trixie] Update to Debian Trixie and Python 12
OpenVoiceOS/ovos-docker pull request #61
Opened 2024-09-29 22:51 UTC by goldyfruit

Closing [Alpine](https://github.com/OpenVoiceOS/ovos-docker/pull/56) tentative as TensorFlow doesn't compile with MUSL.

2024-10-03 07:21 UTC, j1nx requested changes
Will run the different containers and report any issues found in separate comments

2024-10-03 07:21 UTC, j1nx commented on audio/files/entrypoint.sh
> +audio_list_state=~/.local/state/audio.state
Can we save these into a mycroft or ovos folder?

```
audio_list_state=~/.local/state/mycroft/audio.state
```
That way I only have to p[ass on that mycroft folder as volume intro the container instead of the overall users state directory itself.

2024-10-03 07:21 UTC, j1nx commented on audio/files/requirements.txt
> +pyalsaaudio
Thx, this will solve https://github.com/OpenVoiceOS/ovos-docker/issues/60

2024-10-03 07:21 UTC, j1nx commented on cli/files/requirements.txt
> +git+https://github.com/OpenVoiceOS/ovos-cli-client.git
Aren't stable containers suposed to pull everything from PyPi? This might cause problems after the stable release in combination of automatic build releases.

2024-10-03 07:21 UTC, j1nx commented on listener/files/entrypoint.sh
> +listener_list_state=/.local/state/listener.state
See above...

2024-10-03 07:21 UTC, j1nx commented on phal-admin/files/entrypoint.sh
> +phal_admin_list_state=~/.local/state/phal_admin.state
Ditto

2024-10-03 07:21 UTC, j1nx commented on phal/files/entrypoint.sh
> +phal_list_state=~/local/state/phal.state
Same same

2024-10-03 07:29 UTC, j1nx commented
## ovos-phal

I run the ovos-phal container with below phal.list file
```
ovos-phal-plugin-ipgeo>=0.1.0,<1.0.0
ovos-PHAL-plugin-connectivity-events>=0.0.1,<1.0.0
ovos-PHAL-plugin-oauth>=0.0.1,<1.0.0
ovos-PHAL-plugin-wifi-setup>=1.0.0,<2.0.0
ovos-phal-plugin-alsa>=0.0.1,<1.0.0
ovos-phal-plugin-system>=0.1.0,<1.0.0
ovos-PHAL-plugin-network-manager>=0.0.1,<2.0.0
ovos-PHAL-plugin-wallpaper-manager>=0.0.1,<1.0.0
ovos-PHAL-plugin-hotkeys>=0.0.0,<1.0.0
```
I believe the oauth plugin requires Pillow and QRcode packages however Pillow can not be installed at runtime of the container. Perhaps it is best to pre-install and ship with Pillow? I saw it was there before but got removed later?

Below the last section of the rather long error log.
```
Oct 03 06:45:59 OpenVoiceOS ovos-phal[7628]:   ERROR: Failed building wheel for pillow
Oct 03 06:45:59 OpenVoiceOS ovos-phal[7628]:   Building wheel for qrcode (pyproject.toml): started
Oct 03 06:46:00 OpenVoiceOS ovos-phal[7628]:   Building wheel for qrcode (pyproject.toml): finished with status 'done'
Oct 03 06:46:00 OpenVoiceOS ovos-phal[7628]:   Created wheel for qrcode: filename=qrcode-7.3.1-py3-none-any.whl size=40385 sha256=344da74eb5e0605cbf9b741eedd3b77a6353b852f461304808f0a4ba19492125
Oct 03 06:46:00 OpenVoiceOS ovos-phal[7628]:   Stored in directory: /tmp/pip-ephem-wheel-cache-202ioak4/wheels/23/13/8b/59ae3d8bf84ad9a4ce3b3f5a50932989bdc6264b361e1ba048
Oct 03 06:46:00 OpenVoiceOS ovos-phal[7628]: Successfully built qrcode
Oct 03 06:46:00 OpenVoiceOS ovos-phal[7628]: Failed to build pillow
Oct 03 06:46:00 OpenVoiceOS ovos-phal[7628]: ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pillow)
```

2024-10-03 08:34 UTC, j1nx commented
## ovos-core

I run the ovos-core image with the below skills.list;
```
ovos-skill-fallback-unknown>=0.0.4,<1.0.0
ovos-skill-alerts>=0.0.1,<1.0.0
ovos-skill-personal>=0.0.4,<1.0.0
ovos-skill-date-time>=0.2.3,<1.0.0
ovos-skill-hello-world>=0.0.4,<1.0.0
skill-wordnet>=0.0.1,<1.0.0
ovos-skill-spelling>=0.1.0,<1.0.0
ovos-skill-boot-finished>=0.1.0,<1.0.0
ovos-skill-audio-recording>=0.1.0,<1.0.0
ovos-skill-dictation>=0.1.0,<1.0.0
ovos-skill-parrot>=0.0.1,<1.0.0
ovos-skill-volume>=0.0.2,<1.0.0
ovos-skill-naptime>=0.2.3,<1.0.0
ovos-skill-homescreen>=0.0.3,<1.0.0
ovos-skill-weather>=0.0.1,<1.0.0
skill-ddg>=0.0.2,<1.0.0
skill-wolfie>=0.2.0,<1.0.0
ovos-skill-wikipedia>=0.5.0,<1.0.0
skill-ovos-fallback-chatgpt>=0.0.2,<1.0.0
ovos-skill-wikihow>=0.2.0,<1.0.0
ovos-skill-speedtest>=0.1.0,<1.0.0
ovos-skill-ip>=0.1.0,<1.0.0
ovos-skill-somafm>=0.0.2,<1.0.0
skill-news>=0.0.4,<1.0.0
ovos-skill-pyradios>=0.1.0,<1.0.0
ovos-skill-local-media>=0.2.0,<1.0.0
ovos-skill-youtube-music>=0.1.1,<1.0.0
```

All seems to work OK with only te below one error line about Padatious not being installed;

```
Oct 03 07:34:38 OpenVoiceOS ovos-core[8114]: 2024-10-03 07:34:38.243 - skills - ovos_core.intent_services:__init__:62 - ERROR - Failed to create padatious intent handlers, padatious not installed
```

2024-10-03 09:15 UTC, j1nx commented
## ovos-audio

ovos-audio also seems to work as expected. I run the container with the below audio.list;
```
ovos-tts-plugin-server>=0.0.2, <1.0.0
ovos_audio_plugin_simple>=0.1.0, <1.0.0
ovos-audio-plugin-mpv>=0.0.1, <1.0.0
ovos-media-plugin-spotify>=0.2.3, <1.0.0
ovos-media-plugin-chromecast>=0.1.0, <1.0.0
ovos_plugin_common_play[extractors]>=0.0.7, <2.0.0
```

Which only give the below known error bout the g2p mimic plugin;
```
Oct 03 09:12:56 OpenVoiceOS ovos-audio[9168]: 2024-10-03 09:12:56.856 - audio - ovos_plugin_manager.g2p:create:121 - ERROR - The selected G2P plugin could not be loaded.
Oct 03 09:12:56 OpenVoiceOS ovos-audio[9168]: Traceback (most recent call last):
Oct 03 09:12:56 OpenVoiceOS ovos-audio[9168]:   File "/home/ovos/.venv/lib/python3.12/site-packages/ovos_plugin_manager/g2p.py", line 118, in create
Oct 03 09:12:56 OpenVoiceOS ovos-audio[9168]:     g2p = clazz(g2p_config)
Oct 03 09:12:56 OpenVoiceOS ovos-audio[9168]:           ^^^^^^^^^^^^^^^^^
Oct 03 09:12:56 OpenVoiceOS ovos-audio[9168]: TypeError: 'NoneType' object is not callable
```

2024-10-03 09:51 UTC, j1nx commented
## ovos-listener

All good, see below full log;
```
Oct 03 09:48:46 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:46.006 - voice - ovos_dinkum_listener.service:__init__:159 - INFO - Starting Voice Service
Oct 03 09:48:46 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:46.033 - voice - ovos_dinkum_listener.service:on_alive:94 - INFO - DinkumVoiceService is alive.
Oct 03 09:48:46 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:46.034 - voice - ovos_dinkum_listener.service:_before_start:349 - INFO - Starting service...
Oct 03 09:48:46 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:46.253 - voice - ovos_dinkum_listener.service:_connect_to_bus:451 - INFO - Connected to Mycroft Core message bus
Oct 03 09:48:47 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:47.682 - voice - ovos_dinkum_listener.service:on_alive:94 - INFO - DinkumVoiceService is alive.
Oct 03 09:48:47 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:47.747 - voice - ovos_dinkum_listener.voice_loop.hotwords:load_hotword_engines:115 - INFO - creating hotword engines
Oct 03 09:48:47 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:47.754 - voice - ovos_plugin_manager.wakewords:load_module:139 - INFO - Loading "hey_mycroft" wake word via ovos-ww-plugin-precise-lite with config: {'module': 'ovos-ww-pl
ugin-precise-lite', 'model': 'https://github.com/OpenVoiceOS/precise-lite-models/raw/master/wakewords/en/hey_mycroft.tflite', 'expected_duration': 3, 'trigger_level': 3, 'sensitivity': 0.5, 'listen': True, 'fallback_ww': 'hey_mycroft_ope
nwakeword', 'sound': 'snd/start_listening.wav'}
Oct 03 09:48:48 OpenVoiceOS ovos-listener[9549]: /home/ovos/.venv/lib/python3.12/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
Oct 03 09:48:48 OpenVoiceOS ovos-listener[9549]:   setattr(self, word, getattr(machar, word).flat[0])
Oct 03 09:48:48 OpenVoiceOS ovos-listener[9549]: /home/ovos/.venv/lib/python3.12/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
Oct 03 09:48:48 OpenVoiceOS ovos-listener[9549]:   return self._float_to_str(self.smallest_subnormal)
Oct 03 09:48:48 OpenVoiceOS ovos-listener[9549]: /home/ovos/.venv/lib/python3.12/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
Oct 03 09:48:48 OpenVoiceOS ovos-listener[9549]:   setattr(self, word, getattr(machar, word).flat[0])
Oct 03 09:48:48 OpenVoiceOS ovos-listener[9549]: /home/ovos/.venv/lib/python3.12/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
Oct 03 09:48:48 OpenVoiceOS ovos-listener[9549]:   return self._float_to_str(self.smallest_subnormal)
Oct 03 09:48:49 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:49.765 - voice - ovos_plugin_manager.wakewords:load_module:146 - INFO - Loaded the Wake Word hey_mycroft with module ovos-ww-plugin-precise-lite
Oct 03 09:48:49 OpenVoiceOS ovos-listener[9549]: INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Oct 03 09:48:49 OpenVoiceOS ovos-listener[9549]: INFO: XNNPack weight cache not enabled.
Oct 03 09:48:49 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:49.783 - voice - ovos_dinkum_listener.voice_loop.hotwords:load_hotword_engines:164 - INFO - Loading hotword: hey_mycroft with engine: <ovos_ww_plugin_precise_lite.PreciseL
iteHotwordPlugin object at 0xffff327906b0>
Oct 03 09:48:49 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:49.788 - voice - ovos_plugin_manager.wakewords:load_module:139 - INFO - Loading "wake_up" wake word via ovos-ww-plugin-vosk with config: {'module': 'ovos-ww-plugin-vosk',
'rule': 'fuzzy', 'samples': ['wake up'], 'lang': 'en-us', 'wakeup': True, 'fallback_ww': 'wake_up_pocketsphinx'}
Oct 03 09:48:49 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:49.815 - voice - ovos_plugin_manager.wakewords:load_module:146 - INFO - Loaded the Wake Word wake_up with module ovos-ww-plugin-vosk
Oct 03 09:48:49 OpenVoiceOS ovos-listener[9549]: LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=10 max-active=3000 lattice-beam=2
Oct 03 09:48:49 OpenVoiceOS ovos-listener[9549]: LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
Oct 03 09:48:50 OpenVoiceOS ovos-listener[9549]: LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 0 orphan nodes.
Oct 03 09:48:50 OpenVoiceOS ovos-listener[9549]: LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 0 orphan components.
Oct 03 09:48:50 OpenVoiceOS ovos-listener[9549]: LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from /home/ovos/.local/share/vosk/vosk-model-small-en-us-0/ivector/final.ie
Oct 03 09:48:50 OpenVoiceOS ovos-listener[9549]: LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
Oct 03 09:48:50 OpenVoiceOS ovos-listener[9549]: LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
Oct 03 09:48:50 OpenVoiceOS ovos-listener[9549]: LOG (VoskAPI:ReadDataFiles():model.cc:282) Loading HCL and G from /home/ovos/.local/share/vosk/vosk-model-small-en-us-0/graph/HCLr.fst /home/ovos/.local/share/vosk/vosk-model-small-en-us-0
/graph/Gr.fst
Oct 03 09:48:51 OpenVoiceOS ovos-listener[9549]: LOG (VoskAPI:ReadDataFiles():model.cc:308) Loading winfo /home/ovos/.local/share/vosk/vosk-model-small-en-us-0/graph/phones/word_boundary.int
Oct 03 09:48:51 OpenVoiceOS ovos-listener[9549]: LOG (VoskAPI:UpdateGrammarFst():recognizer.cc:287) ["wake up", "[unk]"]
Oct 03 09:48:51 OpenVoiceOS ovos-listener[9549]: LOG (VoskAPI:Estimate():language_model.cc:142) Estimating language model with ngram-order=2, discount=0.5
Oct 03 09:48:51 OpenVoiceOS ovos-listener[9549]: LOG (VoskAPI:OutputToFst():language_model.cc:209) Created language model with 4 states and 7 arcs.
Oct 03 09:48:51 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:51.286 - voice - ovos_dinkum_listener.voice_loop.hotwords:load_hotword_engines:164 - INFO - Loading hotword: wake_up with engine: <ovos_ww_plugin_vosk.VoskWakeWordPlugin o
bject at 0xffff31bf1250>
Oct 03 09:48:51 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:51.288 - voice - ovos_dinkum_listener.voice_loop.hotwords:load_hotword_engines:208 - WARNING - No stop words loaded
Oct 03 09:48:51 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:51.293 - voice - ovos_dinkum_listener.voice_loop.voice_loop:start:177 - INFO - Listening mode: ListeningMode.WAKEWORD
Oct 03 09:48:51 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:51.319 - voice - ovos_dinkum_listener.service:on_started:98 - INFO - DinkumVoiceService started.
Oct 03 09:48:51 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:51.321 - voice - ovos_dinkum_listener.service:on_started:98 - INFO - DinkumVoiceService started.
Oct 03 09:48:51 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:51.322 - voice - ovos_dinkum_listener.service:on_ready:90 - INFO - DinkumVoiceService is ready.
Oct 03 09:48:51 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:51.323 - voice - ovos_dinkum_listener.service:run:326 - INFO - Service ready
Oct 03 09:48:51 OpenVoiceOS ovos-listener[9549]: 2024-10-03 09:48:51.325 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:203 - INFO - Starting loop in mode: ListeningMode.WAKEWORD
```

2024-10-03 09:56 UTC, j1nx commented
## ovos-gui-websocket

Running all fine with one ERROR which is not a big deal and easy to fix;
```
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.151 - gui - ovos_gui.service:on_alive:14 - INFO - Gui Service is alive.
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.501 - gui - ovos_gui.service:_init_bus_client:53 - INFO - Connected to messagebus
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.511 - gui - ovos_gui.extensions:activate_extension:46 - INFO - Creating GUI with config={'idle_display_skill': 'skill-ovos-homescreen.openvoiceos', 'extension': '
ovos-gui-plugin-shell-companion', 'generic': {'homescreen_supported': True}, 'gui_file_host_path': '/home/ovos/.cache/gui_files', 'module': 'ovos-gui-plugin-shell-companion'}
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.602 - gui - ovos_gui_plugin_shell_companion:__init__:43 - INFO - OVOS Shell: Initializing
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.618 - gui - ovos_gui_plugin_shell_companion.color_manager:provide_theme:73 - ERROR - [Errno 2] No such file or directory: '/etc/xdg'
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.621 - gui - ovos_gui_plugin_shell_companion.wigets:__init__:38 - INFO - Notification & Widgets Plugin Initalized
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.624 - gui - ovos_gui_plugin_shell_companion.brightness:start:57 - INFO - auto dim enabled: False
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.626 - gui - ovos_gui_plugin_shell_companion.brightness:start:58 - INFO - auto night mode enabled: False
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.756 - gui - ovos_gui.extensions:activate_extension:58 - INFO - Extensions Manager - Activated: ovos-gui-plugin-shell-companion (OVOSShellCompanionExtension)
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.764 - gui - ovos_gui.bus:create_gui_service:60 - INFO - Starting message bus for GUI...
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.771 - gui - ovos_gui.bus:create_gui_service:72 - INFO - GUI Message bus started!
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.773 - gui - ovos_gui.namespace:_get_idle_display_config:97 - INFO - Configured homescreen: skill-ovos-homescreen.openvoiceos
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.775 - gui - ovos_gui.namespace:_get_active_gui_extension:109 - INFO - Configured GUI extension: ovos-gui-plugin-shell-companion
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.777 - gui - ovos_gui.namespace:_upload_system_resources:1046 - INFO - Removing existing system resources before updating
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.831 - gui - ovos_gui.service:on_ready:18 - INFO - Gui Service is ready.
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.832 - gui - ovos_gui.service:run:77 - INFO - GUI Service Ready
Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.833 - gui - ovos_gui.__main__:on_ready:10 - INFO - GUI websocket started!
```
Just a matter of mkdir the /etc/xdg directory within the image.

2024-10-03 10:08 UTC, j1nx commented
## ovos-gui-shell

All good;
```
Oct 03 10:00:27 OpenVoiceOS systemd[579]: Started OpenVoiceOS GUI Service.
Oct 03 10:00:27 OpenVoiceOS ovos-gui-shell[10356]: 30c74fe4a82211fdfbad27c3bc3a43d7216e098a6113ea7770e27c54e940977c
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: kf.kirigami: The style does not provide a C++ Units implementation. QML Units implementations are no longer supported.
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qml: Fake Brightness Value: 1
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/main.qml:316:9: QML FastBlur: Cannot anchor to an item that isn't a parent or sibling.
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/panel/quicksettings/MuteDelegate.qml:53:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) {
 ... }
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/panel/quicksettings/VolumeSlider.qml:57:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) {
 ... }
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/panel/quicksettings/BrightnessSlider.qml:42:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments
>) { ... }
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/panel/SlidingPanel.qml:46:9: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/NotificationsSystem.qml:45:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/NotificationsSystem.qml:22:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/ListenerAnimation.qml:18:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/qml/SkillView.qml:63:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/osd/VolumeOSD.qml:39:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/StatusIndicator.qml:165:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/ServiceWatcher.qml:33:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: error activating kdeconnectd: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kdeconnect was not provided by any .service files")
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: error activating kdeconnectd: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name org.kde.kdeconnect was not provided by any .service files")
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: kdeconnect.interfaces: dbus interface not valid
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/main.qml:88:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/main.qml:72:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Oct 03 10:00:30 OpenVoiceOS ovos-gui-shell[10370]: qrc:/main.qml:62:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: qrc:/OAuthQrCodeLoader.qml:82:21: Unable to assign [undefined] to QUrl
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: qrc:/OAuthQrCodeLoader.qml:82:21: Unable to assign [undefined] to QUrl
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: qrc:/main.qml:316:9: QML FastBlur: Cannot anchor to an item that isn't a parent or sibling.
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: qrc:/OAuthQrCodeLoader.qml:82:21: Unable to assign [undefined] to QUrl
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: qrc:/main.qml:316:9: QML FastBlur: Cannot anchor to an item that isn't a parent or sibling.
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: qrc:/OAuthQrCodeLoader.qml:82:21: Unable to assign [undefined] to QUrl
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: qrc:/main.qml:316:9: QML FastBlur: Cannot anchor to an item that isn't a parent or sibling.
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: qrc:/OAuthQrCodeLoader.qml:82:21: Unable to assign [undefined] to QUrl
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: qrc:/main.qml:316:9: QML FastBlur: Cannot anchor to an item that isn't a parent or sibling.
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: qml: Trying to connect to Mycroft
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: mycroft connection not open!
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: Fetching from folder:  "/usr/share/OVOS/ColorSchemes"
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: Found  7  files
Oct 03 10:00:31 OpenVoiceOS ovos-gui-shell[10370]: Main Socket connected, trying to connect gui
Oct 03 10:00:32 OpenVoiceOS ovos-gui-shell[10370]: Received port 18181 for gui "{84730fe4-0869-489b-916a-60102f619e7f}"
```

2024-10-03 10:12 UTC, j1nx commented
## ovos-messagebus

All good;
```
Oct 03 10:11:34 OpenVoiceOS ovos-messagebus[10635]: 2024-10-03 10:11:34.476 - bus - ovos_messagebus.__main__:main:46 - INFO - Starting message bus service...
Oct 03 10:11:34 OpenVoiceOS ovos-messagebus[10635]: 2024-10-03 10:11:34.478 - bus - ovos_messagebus.load_config:load_message_bus_config:33 - INFO - Loading message bus configs
Oct 03 10:11:34 OpenVoiceOS ovos-messagebus[10635]: 2024-10-03 10:11:34.487 - bus - ovos_messagebus.__main__:on_ready:32 - INFO - Message bus service started!
```

2024-10-03 11:07 UTC, goldyfruit commented
> ## ovos-phal
> I run the ovos-phal container with below phal.list file
> 
> ```
> ovos-phal-plugin-ipgeo>=0.1.0,<1.0.0
> ovos-PHAL-plugin-connectivity-events>=0.0.1,<1.0.0
> ovos-PHAL-plugin-oauth>=0.0.1,<1.0.0
> ovos-PHAL-plugin-wifi-setup>=1.0.0,<2.0.0
> ovos-phal-plugin-alsa>=0.0.1,<1.0.0
> ovos-phal-plugin-system>=0.1.0,<1.0.0
> ovos-PHAL-plugin-network-manager>=0.0.1,<2.0.0
> ovos-PHAL-plugin-wallpaper-manager>=0.0.1,<1.0.0
> ovos-PHAL-plugin-hotkeys>=0.0.0,<1.0.0
> ```
> 
> I believe the oauth plugin requires Pillow and QRcode packages however Pillow can not be installed at runtime of the container. Perhaps it is best to pre-install and ship with Pillow? I saw it was there before but got removed later?
> 
> Below the last section of the rather long error log.
> 
> ```
> Oct 03 06:45:59 OpenVoiceOS ovos-phal[7628]:   ERROR: Failed building wheel for pillow
> Oct 03 06:45:59 OpenVoiceOS ovos-phal[7628]:   Building wheel for qrcode (pyproject.toml): started
> Oct 03 06:46:00 OpenVoiceOS ovos-phal[7628]:   Building wheel for qrcode (pyproject.toml): finished with status 'done'
> Oct 03 06:46:00 OpenVoiceOS ovos-phal[7628]:   Created wheel for qrcode: filename=qrcode-7.3.1-py3-none-any.whl size=40385 sha256=344da74eb5e0605cbf9b741eedd3b77a6353b852f461304808f0a4ba19492125
> Oct 03 06:46:00 OpenVoiceOS ovos-phal[7628]:   Stored in directory: /tmp/pip-ephem-wheel-cache-202ioak4/wheels/23/13/8b/59ae3d8bf84ad9a4ce3b3f5a50932989bdc6264b361e1ba048
> Oct 03 06:46:00 OpenVoiceOS ovos-phal[7628]: Successfully built qrcode
> Oct 03 06:46:00 OpenVoiceOS ovos-phal[7628]: Failed to build pillow
> Oct 03 06:46:00 OpenVoiceOS ovos-phal[7628]: ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pillow)
> ```

`pillow` was just a test with Alpine, I'm gonna check if it can be installed in `sound-base` container.

2024-10-03 18:03 UTC, JarbasAl commented
> `pillow` was just a test with Alpine, I'm gonna check if it can be installed in `sound-base` container.

should probably be present in PHAL and skills, not needed in sound

2024-10-04 18:42 UTC, goldyfruit commented
> ## ovos-core
> I run the ovos-core image with the below skills.list;
> 
> ```
> ovos-skill-fallback-unknown>=0.0.4,<1.0.0
> ovos-skill-alerts>=0.0.1,<1.0.0
> ovos-skill-personal>=0.0.4,<1.0.0
> ovos-skill-date-time>=0.2.3,<1.0.0
> ovos-skill-hello-world>=0.0.4,<1.0.0
> skill-wordnet>=0.0.1,<1.0.0
> ovos-skill-spelling>=0.1.0,<1.0.0
> ovos-skill-boot-finished>=0.1.0,<1.0.0
> ovos-skill-audio-recording>=0.1.0,<1.0.0
> ovos-skill-dictation>=0.1.0,<1.0.0
> ovos-skill-parrot>=0.0.1,<1.0.0
> ovos-skill-volume>=0.0.2,<1.0.0
> ovos-skill-naptime>=0.2.3,<1.0.0
> ovos-skill-homescreen>=0.0.3,<1.0.0
> ovos-skill-weather>=0.0.1,<1.0.0
> skill-ddg>=0.0.2,<1.0.0
> skill-wolfie>=0.2.0,<1.0.0
> ovos-skill-wikipedia>=0.5.0,<1.0.0
> skill-ovos-fallback-chatgpt>=0.0.2,<1.0.0
> ovos-skill-wikihow>=0.2.0,<1.0.0
> ovos-skill-speedtest>=0.1.0,<1.0.0
> ovos-skill-ip>=0.1.0,<1.0.0
> ovos-skill-somafm>=0.0.2,<1.0.0
> skill-news>=0.0.4,<1.0.0
> ovos-skill-pyradios>=0.1.0,<1.0.0
> ovos-skill-local-media>=0.2.0,<1.0.0
> ovos-skill-youtube-music>=0.1.1,<1.0.0
> ```
> 
> All seems to work OK with only te below one error line about Padatious not being installed;
> 
> ```
> Oct 03 07:34:38 OpenVoiceOS ovos-core[8114]: 2024-10-03 07:34:38.243 - skills - ovos_core.intent_services:__init__:62 - ERROR - Failed to create padatious intent handlers, padatious not installed
> ```

Supposed to be installed via https://github.com/OpenVoiceOS/ovos-core/blob/dev/requirements/lgpl.txt#L1

2024-10-04 18:54 UTC, goldyfruit commented on audio/files/entrypoint.sh
> +audio_list_state=~/.local/state/audio.state
https://github.com/OpenVoiceOS/ovos-docker/pull/61/commits/5620ff16dcdf3e2c9ca0cf248b476a7917230074

2024-10-04 18:54 UTC, goldyfruit commented on phal-admin/files/entrypoint.sh
> +phal_admin_list_state=~/.local/state/phal_admin.state
https://github.com/OpenVoiceOS/ovos-docker/pull/61/commits/5620ff16dcdf3e2c9ca0cf248b476a7917230074

2024-10-04 18:54 UTC, goldyfruit commented on phal/files/entrypoint.sh
> +phal_list_state=~/local/state/phal.state
https://github.com/OpenVoiceOS/ovos-docker/pull/61/commits/5620ff16dcdf3e2c9ca0cf248b476a7917230074

2024-10-04 18:54 UTC, goldyfruit commented
> ## ovos-gui-websocket
> Running all fine with one ERROR which is not a big deal and easy to fix;
> 
> ```
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.151 - gui - ovos_gui.service:on_alive:14 - INFO - Gui Service is alive.
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.501 - gui - ovos_gui.service:_init_bus_client:53 - INFO - Connected to messagebus
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.511 - gui - ovos_gui.extensions:activate_extension:46 - INFO - Creating GUI with config={'idle_display_skill': 'skill-ovos-homescreen.openvoiceos', 'extension': '
> ovos-gui-plugin-shell-companion', 'generic': {'homescreen_supported': True}, 'gui_file_host_path': '/home/ovos/.cache/gui_files', 'module': 'ovos-gui-plugin-shell-companion'}
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.602 - gui - ovos_gui_plugin_shell_companion:__init__:43 - INFO - OVOS Shell: Initializing
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.618 - gui - ovos_gui_plugin_shell_companion.color_manager:provide_theme:73 - ERROR - [Errno 2] No such file or directory: '/etc/xdg'
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.621 - gui - ovos_gui_plugin_shell_companion.wigets:__init__:38 - INFO - Notification & Widgets Plugin Initalized
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.624 - gui - ovos_gui_plugin_shell_companion.brightness:start:57 - INFO - auto dim enabled: False
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.626 - gui - ovos_gui_plugin_shell_companion.brightness:start:58 - INFO - auto night mode enabled: False
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.756 - gui - ovos_gui.extensions:activate_extension:58 - INFO - Extensions Manager - Activated: ovos-gui-plugin-shell-companion (OVOSShellCompanionExtension)
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.764 - gui - ovos_gui.bus:create_gui_service:60 - INFO - Starting message bus for GUI...
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.771 - gui - ovos_gui.bus:create_gui_service:72 - INFO - GUI Message bus started!
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.773 - gui - ovos_gui.namespace:_get_idle_display_config:97 - INFO - Configured homescreen: skill-ovos-homescreen.openvoiceos
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.775 - gui - ovos_gui.namespace:_get_active_gui_extension:109 - INFO - Configured GUI extension: ovos-gui-plugin-shell-companion
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.777 - gui - ovos_gui.namespace:_upload_system_resources:1046 - INFO - Removing existing system resources before updating
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.831 - gui - ovos_gui.service:on_ready:18 - INFO - Gui Service is ready.
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.832 - gui - ovos_gui.service:run:77 - INFO - GUI Service Ready
> Oct 03 09:54:16 OpenVoiceOS ovos-gui-websocket[10229]: 2024-10-03 09:54:16.833 - gui - ovos_gui.__main__:on_ready:10 - INFO - GUI websocket started!
> ```
> 
> Just a matter of mkdir the /etc/xdg directory within the image.

https://github.com/OpenVoiceOS/ovos-docker/pull/61/commits/c75e6319d2f49dd74bd295eb8a73ab826403516b

2024-10-04 19:10 UTC, j1nx commented
> > ## ovos-core
> > I run the ovos-core image with the below skills.list;
> > ```
> > ovos-skill-fallback-unknown>=0.0.4,<1.0.0
> > ovos-skill-alerts>=0.0.1,<1.0.0
> > ovos-skill-personal>=0.0.4,<1.0.0
> > ovos-skill-date-time>=0.2.3,<1.0.0
> > ovos-skill-hello-world>=0.0.4,<1.0.0
> > skill-wordnet>=0.0.1,<1.0.0
> > ovos-skill-spelling>=0.1.0,<1.0.0
> > ovos-skill-boot-finished>=0.1.0,<1.0.0
> > ovos-skill-audio-recording>=0.1.0,<1.0.0
> > ovos-skill-dictation>=0.1.0,<1.0.0
> > ovos-skill-parrot>=0.0.1,<1.0.0
> > ovos-skill-volume>=0.0.2,<1.0.0
> > ovos-skill-naptime>=0.2.3,<1.0.0
> > ovos-skill-homescreen>=0.0.3,<1.0.0
> > ovos-skill-weather>=0.0.1,<1.0.0
> > skill-ddg>=0.0.2,<1.0.0
> > skill-wolfie>=0.2.0,<1.0.0
> > ovos-skill-wikipedia>=0.5.0,<1.0.0
> > skill-ovos-fallback-chatgpt>=0.0.2,<1.0.0
> > ovos-skill-wikihow>=0.2.0,<1.0.0
> > ovos-skill-speedtest>=0.1.0,<1.0.0
> > ovos-skill-ip>=0.1.0,<1.0.0
> > ovos-skill-somafm>=0.0.2,<1.0.0
> > skill-news>=0.0.4,<1.0.0
> > ovos-skill-pyradios>=0.1.0,<1.0.0
> > ovos-skill-local-media>=0.2.0,<1.0.0
> > ovos-skill-youtube-music>=0.1.1,<1.0.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > All seems to work OK with only te below one error line about Padatious not being installed;
> > ```
> > Oct 03 07:34:38 OpenVoiceOS ovos-core[8114]: 2024-10-03 07:34:38.243 - skills - ovos_core.intent_services:__init__:62 - ERROR - Failed to create padatious intent handlers, padatious not installed
> > ```
> 
> Supposed to be installed via https://github.com/OpenVoiceOS/ovos-core/blob/dev/requirements/lgpl.txt#L1

@JarbasAl Could you please have a look?

2024-10-04 19:12 UTC, j1nx commented
Will hopefully have a look at the latest images somewhere this weekend.👍🏻

2024-10-04 19:12 UTC, goldyfruit commented
> Will hopefully have a look at the latest images somewhere this weekend.👍🏻

Images are building :+1:

2024-10-06 17:30 UTC, j1nx commented on phal/files/requirements.txt
> +pillow
https://github.com/OpenVoiceOS/ovos-PHAL-plugin-oauth/issues/23

2024-10-15 16:32 UTC, goldyfruit commented
@j1nx How is your testing, any more suggestions before the merge?

2024-10-21 20:08 UTC, goldyfruit commented
Merging.
Gonna fix on the fly if required.

2024-10-21 20:08 UTC, merged